### ISSUE TITLE
Speeding up the code

### ISSUE THREAD

**Issue by AJJLagerweij** [1iyiwei/topopt#1]
Dear Li-Yi Wei,
I'm working with your code for my thesis and am working on getting rid of some of the 'for' loops in your topopt class. To be more specific those used to generate the global stiffness matrix and the compliance calculations. Would you be interested in the changes that I made?
Regards,
Marb

**Comment by 1iyiwei** [comment]
Sure, feel free to send me a pull request! I am glad my code can be of help.

**Comment by AJJLagerweij** [comment]
Thanks, I send you the one for the proposed stiffness matrix calculator. The increase in speed is significant and the main change was about using numpy bulk operations instead of nested for loops.

I have a code that does the compliance calculations quickly as well (saving 2% time). But it looks really ugly. I'll propose that at the start of next week and hope to make it a bit nicer. 

Lastly most gain can be obtained by changing the filter (the 4 nested for loops). I'll have a look at that next week as well. As the filter is a smoothing operation I'll have a look at codes that do editing of figures.

**Comment by AJJLagerweij** [comment]
I've put the updated compliance calculator in my own fork. But I still dislike the way that it is coded. Do you have any advice?
https://github.com/AJJLagerweij/topopt/blob/1c41cfd9227135a8d2e49f28c7bc2f50b0a5cd6c/src/topopt.py#L75-L90

**Comment by AJJLagerweij** [comment]
Today I've worked on using a faster filter function. In the end the speed gain is around 80% on the example problem. The filter is based upon the same math as in the code of DTU. The main change was made in interpreting it as a kernel convolution as used in image processing. There is an difference however, the way the code works at the boundaries, I use a boundary mirror that allows the use of the same filter in the middle and at the sides (see my fork). I could find no visual difference in the result by inspection. To be sure I'll do a quantitative analysis tomorrow.
https://github.com/AJJLagerweij/topopt/blob/ff731f73a690b61a702888c7d826d1cfece10a7c/src/topopt.py#L116-L142
